/**
 * Tests for domain ID and justification validation
 * 
 * Requirements: 12.4, 12.5
 * - Validate domainId matches pattern ^[a-z0-9_]+_domain$
 * - Validate justification is non-empty string
 * - Return 400 VALIDATION_ERROR on failure
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { 
  isValidDomainId, 
  isValidJustification, 
  validateDomainExclusion,
  ValidationError,
  InvalidRoleError,
  DOMAIN_ID_PATTERN,
  DomainExclusionSchema,
  RoleConfigsSchema,
  mapZodError,
} from '../api/validators';
import { 
  fcConfig, 
  domainIdArb, 
  invalidDomainIdArb,
  validJustificationArb,
  invalidJustificationArb,
} from './test-utils';

describe('Domain ID Validation', () => {
  describe('isValidDomainId', () => {
    /**
     * **Feature: llm-council-production-ready, Property 7: Path Traversal Prevention**
     * (Related: Domain ID validation follows similar pattern-based validation)
     * 
     * *For any* valid domain ID generated by domainIdArb, 
     * isValidDomainId should return true
     * **Validates: Requirements 12.4**
     */
    it('should accept all valid domain IDs matching pattern ^[a-z0-9_]+_domain$', () => {
      fc.assert(
        fc.property(domainIdArb, (domainId) => {
          return isValidDomainId(domainId) === true;
        }),
        fcConfig
      );
    });

    /**
     * *For any* invalid domain ID generated by invalidDomainIdArb,
     * isValidDomainId should return false
     * **Validates: Requirements 12.4**
     */
    it('should reject all invalid domain IDs not matching pattern', () => {
      fc.assert(
        fc.property(invalidDomainIdArb, (domainId) => {
          return isValidDomainId(domainId) === false;
        }),
        fcConfig
      );
    });

    it('should accept specific valid domain IDs', () => {
      expect(isValidDomainId('auth_domain')).toBe(true);
      expect(isValidDomainId('payment_domain')).toBe(true);
      expect(isValidDomainId('user_management_domain')).toBe(true);
      expect(isValidDomainId('api_v2_domain')).toBe(true);
      expect(isValidDomainId('123_domain')).toBe(true);
      expect(isValidDomainId('a_domain')).toBe(true);
    });

    it('should reject specific invalid domain IDs', () => {
      expect(isValidDomainId('auth')).toBe(false);
      expect(isValidDomainId('AUTH_domain')).toBe(false);
      expect(isValidDomainId('auth-domain')).toBe(false);
      expect(isValidDomainId('auth.domain')).toBe(false);
      expect(isValidDomainId('')).toBe(false);
      expect(isValidDomainId('_domain')).toBe(false);
      expect(isValidDomainId('domain_')).toBe(false);
      expect(isValidDomainId('auth domain')).toBe(false);
    });
  });

  describe('DOMAIN_ID_PATTERN', () => {
    it('should be a valid regex pattern', () => {
      expect(DOMAIN_ID_PATTERN).toBeInstanceOf(RegExp);
      expect(DOMAIN_ID_PATTERN.source).toBe('^[a-z0-9_]+_domain$');
    });
  });
});

describe('Justification Validation', () => {
  describe('isValidJustification', () => {
    /**
     * *For any* valid justification (non-empty, non-whitespace string),
     * isValidJustification should return true
     * **Validates: Requirements 12.5**
     */
    it('should accept all valid justifications (non-empty, non-whitespace)', () => {
      fc.assert(
        fc.property(validJustificationArb, (justification) => {
          return isValidJustification(justification) === true;
        }),
        fcConfig
      );
    });

    /**
     * *For any* invalid justification (empty or whitespace-only string),
     * isValidJustification should return false
     * **Validates: Requirements 12.5**
     */
    it('should reject all invalid justifications (empty or whitespace-only)', () => {
      fc.assert(
        fc.property(invalidJustificationArb, (justification) => {
          return isValidJustification(justification) === false;
        }),
        fcConfig
      );
    });

    it('should accept specific valid justifications', () => {
      expect(isValidJustification('This is a valid justification')).toBe(true);
      expect(isValidJustification('a')).toBe(true);
      expect(isValidJustification('  valid with spaces  ')).toBe(true);
    });

    it('should reject specific invalid justifications', () => {
      expect(isValidJustification('')).toBe(false);
      expect(isValidJustification('   ')).toBe(false);
      expect(isValidJustification('\t')).toBe(false);
      expect(isValidJustification('\n')).toBe(false);
    });
  });
});

describe('validateDomainExclusion', () => {
  it('should not throw for valid domain exclusion', () => {
    expect(() => validateDomainExclusion({
      domainId: 'auth_domain',
      justification: 'This domain is being deprecated',
    })).not.toThrow();
  });

  it('should throw ValidationError for invalid domain ID', () => {
    expect(() => validateDomainExclusion({
      domainId: 'invalid',
      justification: 'Valid justification',
    })).toThrow(ValidationError);
  });

  it('should throw ValidationError for empty justification', () => {
    expect(() => validateDomainExclusion({
      domainId: 'auth_domain',
      justification: '',
    })).toThrow(ValidationError);
  });

  it('should throw ValidationError for whitespace-only justification', () => {
    expect(() => validateDomainExclusion({
      domainId: 'auth_domain',
      justification: '   ',
    })).toThrow(ValidationError);
  });

  it('should include correct error code in ValidationError', () => {
    try {
      validateDomainExclusion({
        domainId: 'invalid',
        justification: 'Valid justification',
      });
      expect.fail('Should have thrown ValidationError');
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError);
      expect((error as ValidationError).code).toBe('VALIDATION_ERROR');
      expect((error as ValidationError).statusCode).toBe(400);
      expect((error as ValidationError).field).toBe('domainId');
    }
  });
});

describe('DomainExclusionSchema (Zod)', () => {
  it('should parse valid domain exclusion', () => {
    const result = DomainExclusionSchema.safeParse({
      domainId: 'auth_domain',
      justification: 'This domain is being deprecated',
    });
    expect(result.success).toBe(true);
  });

  it('should reject invalid domain ID', () => {
    const result = DomainExclusionSchema.safeParse({
      domainId: 'invalid',
      justification: 'Valid justification',
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.errors[0].path).toContain('domainId');
    }
  });

  it('should reject empty justification', () => {
    const result = DomainExclusionSchema.safeParse({
      domainId: 'auth_domain',
      justification: '',
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.errors[0].path).toContain('justification');
    }
  });

  it('should reject whitespace-only justification', () => {
    const result = DomainExclusionSchema.safeParse({
      domainId: 'auth_domain',
      justification: '   ',
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.errors[0].path).toContain('justification');
    }
  });

  /**
   * Property test: For any valid domain ID and valid justification,
   * the schema should successfully parse
   * **Validates: Requirements 12.4, 12.5**
   */
  it('should parse all valid domain exclusions', () => {
    fc.assert(
      fc.property(domainIdArb, validJustificationArb, (domainId, justification) => {
        const result = DomainExclusionSchema.safeParse({ domainId, justification });
        return result.success === true;
      }),
      fcConfig
    );
  });
});

describe('Role Name Validation', () => {
  describe('RoleConfigsSchema', () => {
    /**
     * Tests for role name validation against RoleType enum
     * **Validates: Requirements 1.5, 5.1, 5.4**
     */
    it('should accept valid role names from RoleType enum', () => {
      const result = RoleConfigsSchema.safeParse({
        legacy_analysis: { models: [{ model: 'gpt-4o' }] },
        architect: { models: [{ model: 'claude-opus-4-5' }] },
        migration: { models: [{ model: 'gpt-4o' }] },
        security: { models: [{ model: 'gpt-4o' }] },
        aggregator: { models: [{ model: 'gpt-4o' }] },
      });
      expect(result.success).toBe(true);
    });

    it('should reject invalid role names not in RoleType enum', () => {
      const result = RoleConfigsSchema.safeParse({
        invalid_role: { models: [{ model: 'gpt-4o' }] },
      });
      expect(result.success).toBe(false);
      if (!result.success) {
        expect(result.error.errors[0].message).toContain("Invalid role name: 'invalid_role'");
        expect(result.error.errors[0].message).toContain('Valid roles are:');
      }
    });

    it('should reject multiple invalid role names', () => {
      const result = RoleConfigsSchema.safeParse({
        invalid_role1: { models: [{ model: 'gpt-4o' }] },
        invalid_role2: { models: [{ model: 'gpt-4o' }] },
      });
      expect(result.success).toBe(false);
      if (!result.success) {
        expect(result.error.errors.length).toBeGreaterThanOrEqual(2);
      }
    });

    it('should accept undefined role_configs', () => {
      const result = RoleConfigsSchema.safeParse(undefined);
      expect(result.success).toBe(true);
    });

    it('should accept empty role_configs object', () => {
      const result = RoleConfigsSchema.safeParse({});
      expect(result.success).toBe(true);
    });

    it('should accept partial role_configs with valid roles', () => {
      const result = RoleConfigsSchema.safeParse({
        architect: { models: [{ model: 'gpt-4o' }] },
      });
      expect(result.success).toBe(true);
    });
  });

  describe('mapZodError for role validation', () => {
    /**
     * Tests for INVALID_ROLE error code mapping
     * **Validates: Requirements 1.5, 5.1, 5.4**
     */
    it('should return INVALID_ROLE error code for invalid role names', () => {
      const result = RoleConfigsSchema.safeParse({
        invalid_role: { models: [{ model: 'gpt-4o' }] },
      });
      expect(result.success).toBe(false);
      if (!result.success) {
        const mappedError = mapZodError(result.error);
        expect(mappedError.code).toBe('INVALID_ROLE');
        expect(mappedError.message).toContain("Invalid role name: 'invalid_role'");
        expect(mappedError.details).toHaveProperty('invalidRole', 'invalid_role');
        expect(mappedError.details).toHaveProperty('validRoles');
        expect((mappedError.details as any).validRoles).toContain('architect');
        expect((mappedError.details as any).validRoles).toContain('security');
      }
    });

    it('should return VALIDATION_ERROR for non-role validation errors', () => {
      const result = RoleConfigsSchema.safeParse({
        architect: { models: [] }, // Empty models array - min 1 required
      });
      expect(result.success).toBe(false);
      if (!result.success) {
        const mappedError = mapZodError(result.error);
        expect(mappedError.code).toBe('VALIDATION_ERROR');
      }
    });

    it('should include field path in error details', () => {
      const result = RoleConfigsSchema.safeParse({
        bad_role_name: { models: [{ model: 'gpt-4o' }] },
      });
      expect(result.success).toBe(false);
      if (!result.success) {
        const mappedError = mapZodError(result.error);
        expect(mappedError.details).toHaveProperty('field', 'role_configs.bad_role_name');
      }
    });
  });

  describe('InvalidRoleError', () => {
    it('should create error with correct properties', () => {
      const error = new InvalidRoleError('invalid_role', ['architect', 'security']);
      expect(error.code).toBe('INVALID_ROLE');
      expect(error.statusCode).toBe(400);
      expect(error.invalidRole).toBe('invalid_role');
      expect(error.validRoles).toEqual(['architect', 'security']);
      expect(error.message).toContain("Invalid role name: 'invalid_role'");
      expect(error.message).toContain('architect, security');
    });
  });
});
